name: build
on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-18.04, r: '4.0'}
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
      - uses: r-lib/actions/setup-pandoc@master
        with:
          r-version: ${{ matrix.config.r }}
      - name: Install linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-dev libssl-dev libcurl4-openssl-dev libudunits2-dev libopenblas-base
      - name: Define variables
        run: |
          echo "path_repo=$(pwd)" >> $GITHUB_ENV
          echo "path_export=docs" >> $GITHUB_ENV
          echo "repo=$(echo $GITHUB_REPOSITORY | sed 's/.*\///')" >> $GITHUB_ENV
      - name: Check R installation and variables
        run: |
          Rscript -e "print('R installation works!')"
          echo "Github actor: ${GITHUB_ACTOR}"
          echo "Github repository: ${GITHUB_REPOSITORY}"
          echo "Github repo: ${repo}"
          echo "Path repo: ${path_repo}"
          echo "Path export: ${path_export}"
          echo "---------------------------------------------------------------------------------------------"
          echo "Folder contents at $(pwd):"
          ls -lh
          echo "---------------------------------------------------------------------------------------------"
          printenv
          sed --version
      - name: Cache R packages
        id: cache-rp
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ matrix.config.r }}
      - name: Install R dependencies
        if: steps.cache-rp.outputs.cache-hit != 'true'
        run: |
          Rscript -e 'install.packages(c("blogdown"))'
          Rscript -e 'installed.packages()'
          echo ""
          echo "R directory size:"
          du -sh ${{ env.R_LIBS_USER }}
      - name: Hugo setup and status
        run: |
          Rscript -e 'blogdown::install_hugo()'
          Rscript -e 'blogdown::config_Rprofile()'
          Rscript -e 'blogdown::check_hugo()'
          echo ""
          Rscript -e 'blogdown::check_site()'
      - name: Build site
        run: |
          # Render website
          echo "Building website ..."
          Rscript -e "blogdown::build_site()"
          
          # List folder contents
          echo "Folder contents at $(pwd):"
          ls -lh
          echo "Folder contents at ${path_repo}/${path_export}:"
          ls -lh ${path_repo}/${path_export}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./docs

